### PR TITLE
fr-typo

### PR DESCRIPTION
**Pull request by KevinKhau**
- [x ] I did these translations myself and own copyright for them
- [ x] I didn't use a machine to do these translations
- [ x] I assign all copyright to Loom Network for these translations

### CODE REVIEW

**Review by StephanGR — APPROVED** [review]
Nice work :)

**Comment by andreipope** [comment]
@KevinKhau Thanks for taking the time to create this pull request. It looks like some unwanted changes have sneaked in (semicolons). Can you please fix this?

**Comment by KevinKhau** [comment]
@andreipope Thanks for checking this PR. It's fixed. :)

**Comment by andreipope** [comment]
@KevinKhau Awesome, thank you!

**Pull request merged**
