### PR TITLE
Farsi Translation (Chapter 1,2,3)

### PR DESCRIPTION
**Pull request by shayanb**
- [x] I did these translations myself and own copyright for them
- [x] I didn't use a machine to do these translations
- [x] I assign all copyright to Loom Network for these translations

As described in https://github.com/loomnetwork/cryptozombie-lessons/issues/457 this translation is being carried out by multiple people and is peer reviewed before this pull request. 

Please let me know if anything else is needed.

### CODE REVIEW

**Comment by shayanb** [comment]
Any updates on this PR?

**Comment by shayanb** [comment]
Another bump! Is there something in specific blocking this PR?

**Comment by andreipope** [comment]
@shayanb We just merged the PR and will update the website soon. Thank you!

**Comment by shayanb** [comment]
> @shayanb We just merged the PR and will update the website soon. Thank you!

Thanks @andreipope . I haven't been able to spot the translation on the website, is it updated yet?

**Comment by MehranMazhar** [comment]
@andreipope. We are waiting for the website update, thanks

**Comment by shayanb** [comment]
@andreipope just bumping this as still this translation is not visible on the main website. is there a way to directly link to the Farsi translation?

**Pull request merged**
