### PR TITLE
Fix wrongly capitalized variable names in Lesson 6 chapters 7-9

### PR DESCRIPTION
**Pull request by KorbinianK**
- Fixed the error in all languages that included these chapters. 
- No text-translations were changed.

**Was:**
```
function feedOnKitty(zombieId, kittyId) {
      [...]
        return CryptoZombies.methods.feedOnKitty(zombieId, KittyId) 
      [...]
```

**Should be:**
```
function feedOnKitty(zombieId, kittyId) {
      [...]
        return CryptoZombies.methods.feedOnKitty(zombieId, kittyId) 
      [...]
```

### CODE REVIEW

**Comment by eduardonunesp** [comment]
Thanks @KorbinianK

**Comment by eduardonunesp** [comment]
Looks like the branch has so conflicts, could you please fix them @KorbinianK , thanks 👍

**Comment by KorbinianK** [comment]
@eduardonunesp Those conflicts are the fixes...

**Comment by eduardonunesp** [comment]
Nice @KorbinianK, I'll take a look thanks!

**Pull request merged**
