### PR TITLE
Translate lesson 5 into Korean and fix some errors in other resources

### PR DESCRIPTION
**Pull request by studroid**
Translate lesson 5 and fix some errors in other resources (+22 squashed commits)

Squashed commits:
[fcc59e0] Translate chapter 15
[3f373c6] Translate chapter 14
[8d1a6e8] Translate chapter 13
[1be2708] Fix the term for 'comment'
[8e1fc29] Translate chapter 12
[663490f] Translate chapter 11
[a5aa57a] Translate chapter 10
[d66509c] Translate chapter 9
[902c9e5] Translate chapter 8
[decba9c] Translate chapter 7
[b3fa706] Translate chapter 6
[512d9e3] Translate chapter 5
[00134de] Translate chapter 4
[0729fdd] Translate chapter 3
[be90b95] Translate chapter 2
[6ebb00e] Translate chapter 1
[7d49672] Translate chapter 0
[d2ce48f] Translate index.json and share-template-msgs.json
[0d2f216] Fix typos in previous lessons
[cdcdf8b] Add base contents for lesson 5 in index.json and share-template-msgs.json
[cdbe7b0] Add base files
[81b1d71] Fix a typo

- [x] I did these translations myself and own copyright for them
- [x] I didn't use a machine to do these translations
- [x] I assign all copyright to Loom Network for these translations

### CODE REVIEW

**Comment by eduardonunesp** [comment]
hey @studroid thanks for the translations, could you please check if the file `index.ts` is updated too

**Comment by studroid** [comment]
@eduardonunesp Thanks for letting me know! I've just added the contents :)

**Comment by eduardonunesp** [comment]
@studroid just another details on line 118 of `index.json` there's another chapter5 detail to add. Thanks

**Comment by studroid** [comment]
@eduardonunesp OMG, I just missed the detail! Just added them. I have to take more care for lesson 6. 😅 Thanks!

**Comment by eduardonunesp** [comment]
Thanks @studroid

**Pull request merged**
