### PR TITLE
Translation fr - Lesson 5

### PR DESCRIPTION
**Pull request by pl4ym0re**
- [X] I did these translations myself and own copyright for them
- [X] I didn't use a machine to do these translations
- [X] I assign all copyright to Loom Network for these translations

### CODE REVIEW

**Comment by lukezhangstudio** [comment]
@pl4ym0re super thankful for the translation, you are missing one piece here: https://github.com/loomnetwork/cryptozombie-lessons/blob/master/fr/share-template-msgs.json

please translate the corresponding strings from `en`.

thanks so much!

**Comment by 4N1S** [comment]
https://github.com/loomnetwork/cryptozombie-lessons/commit/561e6fc8bbf3d19e296dd71c4f40f2a70f94bebb

**Comment by pl4ym0re** [comment]
@lukezhangstudio Oops sorry for that! I made a new commit: [70d4dcf](https://github.com/loomnetwork/cryptozombie-lessons/pull/186/commits/70d4dcf97ee26cb0db3d67fd4a4e9d71a4bdb336)

**Comment by lukezhangstudio** [comment]
thanks! looks good!

**Pull request merged**
