### PR TITLE
Italian language translation completed for the first course: Solidity

### PR DESCRIPTION
**Pull request by nobady90**
- [ ✔️ ] I did these translations myself and own copyright for them
- [ ✔️ ] I didn't use a machine to do these translations
- [ ✔️ ] I assign all copyright to Loom Network for these translations

Something will probably have escaped but when it will be published I will do the whole tour from lesson 1 to see step by step where I can improve the translation ;-)

### CODE REVIEW

**Review by neo1777 — APPROVED** [review]

**Comment by nobady90** [comment]
anybody who can merge this?

**Comment by andreipope** [comment]
> anybody who can merge this?

Sure thing. Thank you for your effort!

**Review by andreipope — APPROVED** [review]
LGTM

**Comment by nobady90** [comment]
hello, I don't know if I did something wrong but the Italian IT language is not yet visible on [https://cryptozombies.io/](https://cryptozombies.io/)
Maybe I should have added it to the menus?

**Pull request merged**
