### PR TITLE
Translation es - Lesson 5

### PR DESCRIPTION
**Pull request by jjfernandezr**
- [x] I did these translations myself and own copyright for them
- [x] I didn't use a machine to do these translations
- [x] I assign all copyright to Loom Network for these translations

### CODE REVIEW

**Comment by mattkanwisher** [comment]
Thanks! @JSabio take a look please

**Comment by mattkanwisher** [comment]
Thanks !

**Comment by jjfernandezr** [comment]
It's my pleasure to contribute to the project.

**Comment by JuanitoH29** [comment]
Luce bien para mi, pasare este PR al equipo de loom 😉

**Comment by JuanitoH29** [comment]
Y gracias por su colaboracion

**Comment by jjfernandezr** [comment]
De nada, un placer.

**Pull request merged**
